#%RAML 0.8
title: Sample API
version: 1.1
mediaType: application/json

traits:
  - secured: !include traits/secured.yml
  
/messages:
  post:
    is: [secured]
    description: Post messages to the group in any language. If the text is not in english, an english translation will be added as a subtitle.
    body:
      application/json:
        schema: !include schema/json/request/post/Messages.json
        example: !include example/json/request/post/Messages.json
        